package com.rush.model.enums;

/**
 * Created by lynx on 2/20/17.
 */
public enum AppState {

    REGISTRATION, PAY_WITH_POINTS, LOGIN, REDEEM_REWARDS, ISSUE_REWARDS,
    EARN_POINTS, MEMBER_INQUIRY, TRANSACTIONS, GUEST_PURCHASE, OCR, OFFLINE, GIVE_STAMPS, MENU
}
